Us 94/refactoring activities
rdsaliba/notorious-eng pull request #115
Opened 2020-11-23 16:49 UTC by rdsaliba

Inspection fixes
- Code Style issues
- Compiler issues
- Declaration redundancy
- Java language level migration aids
- Javadoc
- Probable bugs
- Proofreading

There's more that needs to be fixed.

2020-11-24 01:05 UTC, PaulMicu commented
Are the changes in these files necessary?
.idea/sonarIssues.xml
cbms.iml

2020-11-24 01:08 UTC, rdsaliba commented on .gitignore
> +.idea/sonarIssues.xml
@PaulMicu 
Hi Paul, as you can see I tried to exclude them in the gitignore but it has failed me every single time...

2020-11-25 00:05 UTC, PaulMicu requested changes

2020-11-25 00:05 UTC, PaulMicu commented on src/main/java/com/cbms/preprocessing/DataPrePreprocessorController.java
>   */
Any reason why you only removed some of the '*' in this file and the others(i'm not gonna leave a comment on them because there's a few)

2020-11-25 23:11 UTC, rdsaliba commented on src/main/java/com/cbms/preprocessing/DataPrePreprocessorController.java
>   */
This was due to automatic fix on intellij, I'll fix those and push the changes. Good catch.

2020-11-26 00:22 UTC, PaulMicu approved these changes

2020-11-26 00:23 UTC, merged