107 add system type
rdsaliba/notorious-eng pull request #149
Opened 2021-01-03 17:44 UTC by jeffbuonamici

User now has the ability to add different system types. System types have a name, description, and parameters(threshold values). The user can add as many threshold values as they need by clicking the "+" button. Once the user clicks save, it gets added into the database.

2021-01-05 22:30 UTC, PaulMicu commented
i dont see where in the UI you can add the system type from the main page, can you clarify, thanks

2021-01-06 20:51 UTC, jeffbuonamici commented
@PaulMicu You can't right now because the page where you would access it is currently being implemented by @najimgh. Simply change "/Systems.fxml" in Main.java to "/AddSystemType.fxml" just to test it.

2021-01-07 01:38 UTC, Shirwarsame reviewed
Code works and is put into the database
System Type Name  and Threshold Name allows just numbers to be accepted
System information needs to be stored somewhere in the database

2021-01-07 18:31 UTC, JayChouteau requested changes
Overall, very good work on the issue. The UI is clean and the code structure follows what was built. I left a few small comments directly on the code. Some of the other feedback:
1) Number of thresholds
This is more about how we want to deal with recommendation labels, but do we want to limit the number of threshold labels that can be assigned to an asset type? Do we want to offer a selection instead of having the user enter his own? This doesn't block the pr or issue but is more food for thought for the team.
2) Mimosa architecture
As we move on and add to our item package, i am wondering if this follows the mimosa architecture. We don't really need to stick to it, but I guess it was our model. Roy might be better to help with this. Plus, this comment doesn't stop the merging of this pull request.

2021-01-07 18:31 UTC, JayChouteau commented on src/main/java/com/cbms/ui/controller/AddSystemTypeController.java
> +    private Button systemMenuButton;
Change the naming to systemMenuBtn (to be consistent with the UI refactoring)

2021-01-07 18:31 UTC, JayChouteau commented on src/main/java/com/cbms/ui/controller/AddSystemTypeController.java
> +    private Button cancelButton;
Change the naming to cancelBtn (to be consistent with the UI refactoring)

2021-01-07 18:31 UTC, JayChouteau commented on src/main/java/com/cbms/ui/controller/AddSystemTypeController.java
> +    private Button savebtn;
-> saveBtn

2021-01-07 18:31 UTC, JayChouteau commented on src/main/resources/AddSystemType.fxml
> +            <Button fx:id="exitMenuButton" contentDisplay="TOP" layoutX="10.0" layoutY="10.0" mnemonicParsing="false" prefHeight="74.0" prefWidth="74.0" style="-fx-background-radius: 0;" stylesheets=
->exitMenuBtn

2021-01-07 18:31 UTC, JayChouteau commented on src/main/resources/css/style.css
>  #addSystemButton
->addSystemButton

2021-01-07 18:31 UTC, JayChouteau commented on src/main/resources/AddSystemType.fxml
> +                            <Image url="@imgs/outline_exit_to_app_white_18dp.png" />
My intellij tells me that I cannot resolve this file. Was this added to our project? I don't see it in the imgs folder.

2021-01-07 18:31 UTC, JayChouteau commented on src/main/java/com/cbms/ui/controller/AddSystemTypeController.java
> +        savebtn.setOnMouseClicked(new EventHandler<MouseEvent>() {
Cap on value
My understanding is that the threshold value is a % of the RUL, meaning that there should be a min value (0) and a max value (100). This should be enforced in the controller.

2021-01-07 18:31 UTC, JayChouteau commented on src/main/resources/AddSystemType.fxml
> +            <TextField fx:id="thresholdName1" layoutX="200.0" layoutY="175.0" prefHeight="25.0" prefWidth="190.0" />
1) Threshold names and values
I feel like UI wise, the labels we put for the threshold name and value are maybe too abstract for users. I feel like changing "Threshold name" and "value" to "Recommendation label" and "Threshold value" might be more explicit for a user.
2) Threshold description
I feel like we should have a description (text) on the UI that explains what the threshold name and values represent for the user to enter information correctly. Either a plain description or a small help button.

2021-01-08 04:57 UTC, jeffbuonamici commented
@JayChouteau I made the variable name changes. The rest of your concerns can be changed once we have more clarification on these issues.

2021-01-10 19:36 UTC, JayChouteau approved these changes

2021-01-10 20:04 UTC, merged