#48 delete a system type
rdsaliba/notorious-eng pull request #195
Opened 2021-01-21 21:15 UTC by PaulMicu

You might need to implement the fix from : https://jeffreyeverhart.com/2017/11/04/mysql-workbench-error-code-2013-lost-connection-mysql-server-query/

This is because there are a lot of measurements and assets to delete in the background when deleting an asset type.
I had to do it for running the sql in the workbench, it might not be necessary when testing the application itself.

When confirming the deletion , it might take a little time to run the delete and go back to the main screen. This is "normal" and we will need to implement a loading screen in the future for all of these kinds of actions that require a load time

This PR resolves #10

2021-01-23 03:39 UTC, najimgh commented
Upon deleting a System Type I get the following error
![Screen Shot 2021-01-22 at 10 37 37 PM](https://user-images.githubusercontent.com/46761237/105567784-9cfbd680-5d02-11eb-86ad-39326b17bb36.png)

2021-01-23 03:41 UTC, najimgh requested changes
Upon deleting a system type I get the following error:
![Screen Shot 2021-01-22 at 10 37 37 PM](https://user-images.githubusercontent.com/46761237/105567834-f6640580-5d02-11eb-92e3-720a0b5e2414.png)

2021-01-23 12:38 UTC, PaulMicu commented
the latest script is V8.1 try that one

2021-01-24 18:45 UTC, rdsaliba commented
Hi Paul, I'm currently running the latest dump file and still another issue got raised from my side. Please see attached screenshot. I was testing from the application.

![Screen Shot 2021-01-24 at 1 27 11 PM](https://user-images.githubusercontent.com/17152773/105640134-4ac5cd00-5e4a-11eb-8b11-3b941c5ca719.png)

2021-01-24 18:51 UTC, PaulMicu commented
@rdsaliba you're not running the lastest version of mariaDB, either your running an older version or you're running mysql. Every time you get an error like this it means that your db is not correct

2021-01-24 18:53 UTC, rdsaliba commented
Currently running MariaDB 10.5.8 with script V8.1

2021-01-24 19:07 UTC, jeffbuonamici commented
I'm running the latest DB V8.1, and it works for me.

2021-01-24 19:29 UTC, rdsaliba approved these changes

2021-01-24 19:58 UTC, jeffbuonamici approved these changes

2021-01-24 20:16 UTC, merged