89 establish a system type threshold
rdsaliba/notorious-eng pull request #199
Opened 2021-01-25 01:00 UTC by PaulMicu

Implemented the saving modification and removal of thresholds, modified add system type to incorporate changes and made some minor changes to the UI

2021-01-25 02:57 UTC, jeffbuonamici approved these changes
Good job.

2021-01-25 22:58 UTC, JayChouteau requested changes
This is a good chunk of code that is added/updated. Overall, very good job on the logic, the update of the UI handling, the addition of UI utilities, and the way we can edit a system type. There are a few refactoring well done when it comes to DAOs and UIs. The main purpose of this pr, which is to establish the thresholds works great! The user can input his thresholds only as of the form of integer value and those values are properly saved in the database. I have some minor (format) review comments as well as some bigger behavioral review comments. The biggest are the following:
1)The save info button stays disabled when editing the system type name or description. Furthermore, it is throwing an exception when editing the description (see snippets).

2) This wasn't part of the acceptance criteria, but I feel that having some relative boundaries on the threshold values would be important. It might be something we overlooked when defining the issue and acceptance criteria, but it doesn't make sense to an "OK" threshold that is lower than the "Warning" threshold. That's why I wrote relative boundaries because the threshold should be bound by the other threshold values. That could be implemented either when trying to save or when typing in the value.

2021-01-25 22:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/SystemTypeController.java
> +        columnFailed.setCellValueFactory(new PropertyValueFactory<>("valueFailed"));
I feel like it would increase the readability of the code if we move all the settings of valuefactory into a different method and call this function from attach events. It is not "extracting" a method to properly say, but it is more regrouping those similar actions under a method that has a self-decriptive name for that set of actions. AttachEvents should only make calls to other functions if possible.

2021-01-25 22:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/SystemTypeController.java
> +
Minor: those 2 lines can be removed.

2021-01-25 22:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/SystemTypeController.java
> +     * @autor Paul
Wrong tag -> author

2021-01-25 22:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/AddSystemTypeController.java
> +
Minor: remove whitespace

2021-01-25 22:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/SystemTypeList.java
> +    private String valueOk, valueCaution, valueAdvisory, valueWarning, valueFailed , id ;
Is the ID needed? It isn't used anywhere and not included in copy constructor either.

2021-01-25 22:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/SystemTypeInfoController.java
> +            if( handleTextChange(newText,originalAssetType.getDescription()))
When calling the handleTextChange for description, it seems like the application is trying to parse a double. Maybe there is something wrong going in the if conditions of the method.
![SetDescription issue](https://user-images.githubusercontent.com/47158909/105775260-86d55c80-5f34-11eb-88d0-3eaa6607e328.PNG)

2021-01-25 22:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/SystemTypeInfoController.java
> +        if (field.equals(originalAssetType.getName()) || field.equals(originalAssetType.getDescription()) && newText.equals(field))
Behaviour: when editing the description or the name, the save button stays disabled. Editing description is throwing the double.parse error while editing the name doesn't throw an exception, but doesn't enable the save button.
![Changing name_can't save](https://user-images.githubusercontent.com/47158909/105775854-86899100-5f35-11eb-9e76-78bcbbec807b.PNG)
![SetDescription_no save](https://user-images.githubusercontent.com/47158909/105775859-88ebeb00-5f35-11eb-840b-3f05bc9e8ef9.PNG)

2021-01-27 21:52 UTC, PaulMicu commented on JavaFXUserInterface/src/main/java/SystemTypeController.java
> +        columnFailed.setCellValueFactory(new PropertyValueFactory<>("valueFailed"));
if it helps, sure

2021-01-28 02:14 UTC, JayChouteau commented
After discussion with @PaulMicu (assignee on this PR), it was decided that the enforcement of relative boundaries was out of scope for this pr and will be added in a future issue.

2021-01-28 02:15 UTC, JayChouteau approved these changes
All the comments from the first review were addressed. Very good job.

2021-01-28 02:15 UTC, merged