220 [Refactoring] Testing files organization
rdsaliba/notorious-eng pull request #259
Opened 2021-02-08 23:23 UTC by t98b

- Separated test files in test folders into Unit and System Tests
- Separated system test cases based on the loaded page

2021-02-09 18:44 UTC, rdsaliba commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_9" default="false" project-jdk-name="15" project-jdk-type="JavaSDK">
This file should have been part of the commit.

2021-02-09 18:51 UTC, rdsaliba approved these changes, later dismissed
Thanks Talal for doing this. I see at last the unit tests are well organized.

2021-02-09 18:57 UTC, rdsaliba requested changes
need to fix merge conflicts and remove the .idea/ file

2021-02-10 00:36 UTC, t98b commented
@rdsaliba I resolved all the issues and updated the branch to be consistent with the develop branch.

2021-02-10 00:42 UTC, rdsaliba commented
Hi @t98b, there's still some conflicts that require your attention.

2021-02-10 03:04 UTC, JayChouteau requested changes
Separating unit test and system into different packages is good. However, I have a few comments to make:
1) I think that unit test files should be named the same as their corresponding source file (with "Test" at the end). Since unit tests are testing single units, it makes sense to have 1-to-1 correspondence between the test files and the src files.
2) I know we had a discussion about this, but thinking back, I think "e2e" makes more sense as a name for the system tests package. The first reason is that our system tests are actually gonna be e2e tests. The second reason is that this seems to be the convention in the industry  and is also what is used in the template provided by the professor
3) I am unsure about the naming for the e2e test files. The reason is that e2e is supposed to test a full feature. Every feature starts from the main screen and then will perform actions on the main screen or other screens. We could separate by scene as you did, but we would need to agree on the separation, like a test should be located in the scene test file where the last action of the test is performed. That sounds a bit confusing to me. Maybe something like division according to Epics would make more sense: "PrognosticAssessement", "Diagnostic Assessment", or something like that.

I know I am being very picky here and some of those comments are personal opinions and maybe others could comment on this. Comment nb#3 is also maybe something that could be completed when we work on adding system tests. Feel free to reach out to discuss this.

2021-02-10 03:04 UTC, JayChouteau commented on JavaFXUserInterface/src/test/java/UnitTests/AddSystemControllerTest.java
> +    }
This start method belongs to a system test. To do the 2 tests mentioned below, there is no need to start the application, The setup method and the tests are enough. This should be removed. Also, the file name should be corresponding to the src file name.

2021-02-10 03:04 UTC, JayChouteau commented on Server/src/test/java/UnitTests/preprocessing/reductionTest.java
> +package UnitTests.preprocessing;
This file should be named with a 1-to-1 correspondence to the src file.

2021-02-16 01:58 UTC, JayChouteau approved these changes

2021-02-16 02:01 UTC, JayChouteau commented on Server/src/test/java/UnitTests/preprocessing/reductionTest.java
> +package UnitTests.preprocessing;
The files were correctly changed to one=to-one correspondence

2021-02-16 02:01 UTC, JayChouteau commented on JavaFXUserInterface/src/test/java/UnitTests/AddSystemControllerTest.java
> +    }
This part will be resolved when new unit test and system tests are being implementend

2021-02-16 15:48 UTC, closed without merging