#217 UI enhancement - Custom Dialog Boxes
rdsaliba/notorious-eng pull request #263
Opened 2021-02-11 08:43 UTC by Shirwarsame

Custom dialog boxes that are in line with the UI.
The four custom dialog boxes can be found by:
1. Clicking an asset and clicking the delete button
2. Clicking on a system type from the system type list and clicking the delete button
3. Clicking the add system button and clicking save (with info or without info)

Any suggestions to change the dialog boxes would appreciated

2021-02-12 14:18 UTC, PaulMicu requested changes
-  All the constant strings should be in in the textconstant file
 - please give an access modifier to all the necessary variables and classes
 - please change the OK to Ok and the CANCEL to Cancel
 - Please Run the intellij code cleanup

2021-02-14 05:42 UTC, jeffbuonamici commented
You're going have to pull from develop and resolve some conflicts that happened due to the latest merged pull request. Should be an easy fix.

2021-02-16 21:55 UTC, PaulMicu requested changes

2021-02-16 21:55 UTC, PaulMicu commented on JavaFXUserInterface/src/main/java/Utilities/CustomDialog.java
> +    CustomDialog(String header, String content, MouseEvent mouseEvent) {
ACCESS MODIFIER !

2021-02-21 03:42 UTC, PaulMicu approved these changes

2021-02-21 16:47 UTC, t98b approved these changes

2021-02-21 18:34 UTC, merged