224 model Z integration
rdsaliba/notorious-eng pull request #268
Opened 2021-02-17 01:04 UTC by Khal-Shah

Includes 4 new models to bring total up to 8.
Z = Random SubSpace, Additive Regression, Multilayer Perceptron and SMOReg.  

Also includes a ModelEvaluation class (potentially useful for F10) that could be used to evaluate models by another testing set, by splitting the training set by percentage or by cross-evaluating training set with a fold (more details in the comments of the class).

Includes unit tests for all new classes. 

Refactoring: the declared type of previous models were changed to use the super type (Classifier). 

This PR closes issue #224

2021-02-17 21:15 UTC, t98b requested changes
Everything looks good.
I think the Evaluation model class will be useful for F10.
But can you move the test files to the Unit Test Folder that has been added.

2021-02-18 01:27 UTC, Khal-Shah commented
> Everything looks good.
> I think the Evaluation model class will be useful for F10.
> But can you move the test files to the Unit Test Folder that has been added.

The new test files have been moved to the unit test folder as requested.
Also, in AssetTypeDAO, I think the previous method was called _getAssetTypeBoundaries_ but once it was changed to _getAssetTypeThresholds_ the RecommendationAssessmentTest was never updated, so I went ahead and made the change (or else the app wouldn't run for me).

2021-02-18 19:19 UTC, t98b approved these changes

2021-02-19 20:50 UTC, najimgh approved these changes
Great addition of the 4 new models. The model evaluation class looks promising and will definitely be useful for issue F10. Code is well commented and understandable.

2021-02-19 21:09 UTC, merged