252 input validation
rdsaliba/notorious-eng pull request #269
Opened 2021-02-19 20:26 UTC by najimgh

Input validation added for the AddAsset form, AddAssetType form and the AssetTypeInfo form

resolves #252

2021-02-20 21:35 UTC, t98b approved these changes

2021-02-21 20:00 UTC, JayChouteau requested changes
The way the input validation errors are highlighted to the user is well done: having the error text fields highlighted in red is clear. However, there are some error messages that are a bit confusing (see comments in the review). All input validations as described in the issue have been performed and work as intended. However, there is one small issue with threshold input validation (see review comments). My last comment is about code duplication. There is a lot of code duplication in this pull-request and it would be better to find ways to get rid of it.

2021-02-21 20:00 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
> +//    private static final String ERROR_HEADER = "Please enter values for all text fields.";
Why is there commented-out code? This should be either deleted or changed.

2021-02-21 20:00 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
> +
Same thing as previous. Commented-out code should be removed or changed.

2021-02-21 20:00 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Utilities/UIUtilities.java
> +
There is a lot of duplication due to the repetition of removeInputError() and createInputError(). The only difference is if the passing argument is a textArea or a textField. It would be better to remove the duplication by having 1 method for each action that allows the passing of an element (either textarea or textfield) and then have a branch condition depending on which one it is within the method. I believe both textarea and textfield are children of TextComponent. This means you could have a TextComponent as a parameter, allowing the function to take in either a textArea or textField and making the distinction within the function.

2021-02-21 20:00 UTC, JayChouteau commented on JavaFXUserInterface/src/main/resources/css/addAsset.css
>  }
There is a lot of duplication between the CSS files for the same code. it would be better to put this on the same CSS file and have it named something more general. Maybe you can reference multiple CSS files in a FXML as well. There is too much duplication.

2021-02-21 20:00 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetTypeController.java
> +        return validForm;
There is no checking for all the above previous thresholds compared to a threshold, it only compares to the first previous. This means that there are no validation if one value is missing. For example, if your warning threshold has no value, then the failed value can be set higher or lower than the caution value or the ok since the validation on failed is made only compared to warning. It would be important to do the validation compared to the first previous non-empty valid input and not just the first previous.

2021-02-21 20:00 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
> +            UIUtilities.createInputError(inputError, errorMessages, assetNameInput, TextConstants.EMPTY_FIELD_ERROR + " and/or \n" + TextConstants.MAX_50_CHARACTERS_ERROR, 65.0, horizontalPosition, 0
This error message is confusing. It would be better to have those 2 conditions separated and have the corresponding message printed depending on the condition triggered.

2021-02-21 20:00 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Utilities/TextConstants.java
> +    public static final String WARNING_FAILED = "The Warning Threshold needs to be larger \nthan the Failed Threshold";
This relates to my previous comment about doing validation on just the previous threshold instead of doing validation on the previous valid threshold. Most likely, the message would be changed.

2021-02-21 21:59 UTC, najimgh commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
> +//    private static final String ERROR_HEADER = "Please enter values for all text fields.";
Removed

2021-02-21 21:59 UTC, najimgh commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
> +
Removed

2021-02-21 22:28 UTC, najimgh commented on JavaFXUserInterface/src/main/java/Utilities/UIUtilities.java
> +
Resolved. The function takes a TextInputControl instead of a textArea or TextField

2021-02-21 23:04 UTC, najimgh commented on JavaFXUserInterface/src/main/resources/css/addAsset.css
>  }
Moved CSS styles to the style.css file

2021-02-21 23:15 UTC, najimgh commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetController.java
> +            UIUtilities.createInputError(inputError, errorMessages, assetNameInput, TextConstants.EMPTY_FIELD_ERROR + " and/or \n" + TextConstants.MAX_50_CHARACTERS_ERROR, 65.0, horizontalPosition, 0
Resolved

2021-02-22 01:42 UTC, najimgh commented on JavaFXUserInterface/src/main/java/Utilities/TextConstants.java
> +    public static final String WARNING_FAILED = "The Warning Threshold needs to be larger \nthan the Failed Threshold";
New error messages added

2021-02-22 01:43 UTC, najimgh commented on JavaFXUserInterface/src/main/java/Controllers/AddAssetTypeController.java
> +        return validForm;
This has been resolved. I have also refactored the code a little more, removing some duplicated code

2021-02-22 01:56 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Utilities/UIUtilities.java
> +
Nice job

2021-02-22 03:10 UTC, JayChouteau approved these changes
Thanks for addressing the comments. This pull-request is approved now.

2021-02-22 03:10 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Utilities/TextConstants.java
> +    public static final String WARNING_FAILED = "The Warning Threshold needs to be larger \nthan the Failed Threshold";
Well done.

2021-02-22 03:11 UTC, merged