#253 back functionality
rdsaliba/notorious-eng pull request #273
Opened 2021-02-22 12:30 UTC by Shirwarsame

Adds back functionality and exit program functionality

resolves #253

2021-02-22 23:40 UTC, rdsaliba requested changes
I kind of agree with Jeremie here. The side bar already acts as navigation control for the user. Also, I think the back button should not appear in the side menu. It would be preferable to have on top of each page.

2021-02-22 23:41 UTC, JayChouteau requested changes
For most screens, the back button takes you back to where you want to be. However, this is hard-coded and could lead the user to confusion, but this strategy will work for now. However, there is a specific place where it didn't make sense to have a back button. I left a comment on the line.

2021-02-22 23:41 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Controllers/AssetTypeController.java
> +        backBtn.setOnMouseClicked(mouseEvent -> uiUtilities.changeScene(mouseEvent, TextConstants.ASSETS_SCENE));
I don't think there should be a back button on the main screens of the side left menu. Asset types screen and assets screen is main screens on their own. A back button for coming back to the assets from the asset types is the same as clicking on the left-side menu.

2021-02-22 23:41 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Controllers/AssetTypeController.java
> +        backBtn.setOnMouseClicked(mouseEvent -> uiUtilities.changeScene(mouseEvent, TextConstants.ASSETS_SCENE));
Also, you could have reached that screen from a specific asset info screen. However, clicking on the back button will always take you back to the assets screen.

2021-02-22 23:42 UTC, rdsaliba commented
I kind of agree with Jeremie here.

2021-02-24 02:58 UTC, JayChouteau commented on JavaFXUserInterface/src/main/java/Controllers/AssetTypeController.java
> +        backBtn.setOnMouseClicked(mouseEvent -> uiUtilities.changeScene(mouseEvent, TextConstants.ASSETS_SCENE));
This issue was addressed

2021-02-24 02:58 UTC, JayChouteau approved these changes

2021-02-24 02:59 UTC, JayChouteau commented
This can be merge as soon as the merge conflicts are resolved

2021-02-24 03:03 UTC, rdsaliba commented
Thanks for addressing the issues Shirwa. This is great.

2021-02-24 03:04 UTC, rdsaliba approved these changes

2021-02-24 04:03 UTC, merged